/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "surface-dim": "#0c1324",
              "secondary-fixed-dim": "#68dba9",
              "on-secondary-container": "#00311f",
              "inverse-on-surface": "#2a3043",
              "surface-container-lowest": "#070d1f",
              "surface-container-low": "#151b2d",
              "on-secondary": "#003825",
              "on-tertiary": "#490080",
              "outline-variant": "#434655",
              "on-tertiary-fixed": "#2c0051",
              "tertiary-fixed": "#f0dbff",
              "background": "#0c1324",
              "tertiary-fixed-dim": "#ddb8ff",
              "surface-container-high": "#23293c",
              "surface-tint": "#b4c5ff",
              "on-primary": "#002a78",
              "on-tertiary-container": "#f9ecff",
              "on-error": "#690005",
              "primary-container": "#2563eb",
              "on-primary-container": "#eeefff",
              "tertiary": "#ddb8ff",
              "on-tertiary-fixed-variant": "#6800b4",
              "secondary": "#68dba9",
              "error": "#ffb4ab",
              "error-container": "#93000a",
              "tertiary-container": "#9637ed",
              "surface-bright": "#33394c",
              "inverse-primary": "#0053db",
              "secondary-container": "#25a475",
              "inverse-surface": "#dce1fb",
              "primary-fixed": "#dbe1ff",
              "surface": "#0c1324",
              "on-secondary-fixed": "#002114",
              "on-secondary-fixed-variant": "#005137",
              "surface-variant": "#2e3447",
              "surface-container-highest": "#2e3447",
              "on-surface": "#dce1fb",
              "outline": "#8d90a0",
              "primary-fixed-dim": "#b4c5ff",
              "on-primary-fixed": "#00174b",
              "secondary-fixed": "#85f8c4",
              "on-background": "#dce1fb",
              "on-surface-variant": "#c3c6d7",
              "primary": "#b4c5ff",
              "on-error-container": "#ffdad6",
              "on-primary-fixed-variant": "#003ea8",
              "surface-container": "#191f31"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "xl": "32px",
              "base_unit": "4px",
              "sm": "8px",
              "margin": "32px",
              "gutter": "24px",
              "xs": "4px",
              "lg": "24px",
              "md": "16px"
      },
      "fontFamily": {
              "headline-lg": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Inter", "sans-serif"],
              "mono-data": ["JetBrains Mono", "monospace"],
              "body-lg": ["Inter", "sans-serif"],
              "body-sm": ["Inter", "sans-serif"],
              "mono-label": ["JetBrains Mono", "monospace"],
              "headline-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "mono-data": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "mono-label": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
